'use strict';
const ENDPOINT='https://script.google.com/macros/s/AKfycbylMatG6GUvgeEbx-i3Vr12ttMGMzqMNc_a1M5c57lUzC_-7ciu_L4irxKmNmCDgLMP/exec';
const COURSE='《我。們。之間的距離》廣東歌音樂劇場';
const $=id=>document.getElementById(id);
let submitting=false,submitted=false;
for(const id of ['regular','student'])for(let i=0;i<=9;i++)$(id).add(new Option(String(i),String(i)));
$('regular').value='1';
function selection(){const regular=Number($('regular').value),student=Number($('student').value);return {regular,student,count:regular+student,price:regular*250+student*200};}
function updateTotal(){const s=selection();$('count').textContent=s.count+' 張';$('total').textContent='HK$'+s.price;$('quantityError').textContent=s.count<1?'請選擇至少 1 張門票。':s.count>9?'每次最多購買 9 張；團體購票請 WhatsApp 查詢。':'';$('submitBtn').disabled=submitting||submitted||s.count<1||s.count>9;}
for(const id of ['regular','student'])$(id).addEventListener('change',updateTotal);
function setPay(mode){const fps=mode==='fps';$('payFps').hidden=!fps;$('payBank').hidden=fps;$('tabFps').setAttribute('aria-pressed',String(fps));$('tabBank').setAttribute('aria-pressed',String(!fps));}
$('tabFps').onclick=()=>setPay('fps');$('tabBank').onclick=()=>setPay('bank');
function buildPayload(){const s=selection();if(!Number.isInteger(s.regular)||!Number.isInteger(s.student)||s.regular<0||s.student<0||s.count<1||s.count>9)throw Error('每次請選購 1 至 9 張門票。');const name=$('fName').value.trim(),phone=$('fPhone').value.trim(),email=$('fEmail').value.trim();if(!name||!phone||!email)throw Error('請填寫姓名、電話及電郵。');const breakdown=`正價 ${s.regular} 張 × HK$250；中學生、大學生及 SVA 學員 ${s.student} 張 × HK$200；共 ${s.count} 張；總額 HK$${s.price}`;return {name,phone,email,course:COURSE,status:'General',enrolmentType:breakdown,session:'2026年10月19日 17:00｜19:00 演後藝人談',remarks:breakdown+($('fNote').value.trim()?'\n備註：'+$('fNote').value.trim():''),price:s.price,sheetTab:'Theatre - 距離 2026'};}
$('ticketForm').addEventListener('submit',async event=>{event.preventDefault();if(submitting||submitted)return;if(!$('ticketForm').reportValidity())return;let data;try{data=buildPayload();}catch(error){$('submitStatus').textContent=error.message;return;}submitting=true;updateTotal();$('submitBtn').textContent='提交中…';$('submitStatus').textContent='';try{await fetch(ENDPOINT,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data)});submitted=true;$('submitStatus').textContent='購票申請已送出，請繼續付款及傳送單據，由 SVA 確認。若未收到電郵，請 WhatsApp 查詢，毋須重複提交。';$('submitBtn').textContent='申請已送出';for(const el of $('ticketForm').querySelectorAll('input,select,textarea'))el.disabled=true;}catch(error){$('submitStatus').textContent='暫時未能確認提交結果。如已付款或曾提交，請先 WhatsApp 查詢，避免重複報名。';$('submitBtn').textContent='重新提交購票申請';}finally{submitting=false;$('successWa').href='https://wa.me/85268984558?text='+encodeURIComponent('你好！我想確認《我。們。之間的距離》購票及付款詳情。姓名：'+data.name+'；電話：'+data.phone+'；'+data.enrolmentType);$('followup').hidden=false;updateTotal();}});
updateTotal();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_ticket_selection',description:'Read current ticket quantities and calculated total. Does not submit an order.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>selection()})).catch(()=>{});}catch{}}
